inherit xilinx-tool-check

XSCT_PATH_ADD = "${XILINX_SDK_TOOLCHAIN}/bin:"
PATH =. "${XSCT_PATH_ADD}"
TOOL_PATH = "${XILINX_SDK_TOOLCHAIN}/bin"
TOOL_VERSION_COMMAND = "hsi -version"
TOOL_VER_MAIN = "${XILINX_VER_MAIN}"
TOOL_NAME = "xsct"
